config/routes.rb
Rails.application.routes.draw do



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  root "bots#index"



  patch "/message", to: "bots#message"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  def index
    @chattings = Chat.all
    @message = Chat.new
  end

  def message
    input_from_user = user_params[:message]
    require "uri"
    require "net/http"
    require "openssl"

    url = URI("https://waifu.p.rapidapi.com/path?user_id=sample_user_id&message=#{input_from_user}&from_name=Boy&to_name=Girl&situation=Developers%20talking%20to%20each%20other.&translate_from=auto&translate_to=auto")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Post.new(url)
    request["content-type"] = "application/json"
    request["X-RapidAPI-Key"] = "9c983ffa95msh7457a831e5d1342p196f2ejsn9449efb04136"
    request["X-RapidAPI-Host"] = "waifu.p.rapidapi.com"
    request.body = "{}"

    response = http.request(request)
    respond_to do |format|
      format.js { render js: "send(#{response.read_body.split("'")}, 'response')" }
    end
  end

  def user_params
    params.require(:chat).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bots/_message.html.erb
<div class='<%= type %>'>
    <%= message %>
</div>

app/views/bots/index.html.erb
<head>
<%= javascript_include_tag "index", "data-turbo-track" => "reload" %>
</head>
<div class="container mt-5">
    <div class="row mt-4">

        <div class="col-md-6 text-center">
            <h1 class="display-2 ">Chat Bot</h1>
            <%= image_tag("bot.gif") %>
        </div>

        <div class="col-md-4 content p-3 mt-5 chat">
            <div class="main">
                   
            </div>
            <div class="input-group">
            <% @chattings.each do |message| %>
                <%= form_for message,url: message_path,id: "message_form", remote: true do |f| %>
                    <%= f.text_field :message, class: "form-control",id: "inputChat",placeholder: "Ask anything to Bot now...." %>
                    <%= button_tag "Send",type: "submit",class: "btn btn-primary btn-lg" do %>
                       Send <i class="far fa-paper-plane p-1"></i>
                    <% end %>                   
                <% end %>
            <% end %>
            </div>
        </div>
    </div>
</div>

<script>
document.getElementById("inputChat").focus();
$("#inputChat").on("keypress", (e) => {
    if (e.keyCode == 13) {
        showInput();
    }
});
</script>

app/views/bots/message.js.erb
function send(message,classOfDiv) {
    let input = document.getElementById("inputChat").value;
    if (input == "") {
        return;
    } else {
        let request = document.createElement("div");
        request.className = classOfDiv;
        request.innerText = message;
        $('.main').appendChild(request);
        document.getElementById("inputChat").value = "";
        let scrollHeight = $('.main').scrollHeight;
        $('.main').scrollTop = scrollHeight + 100;
    }
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatBotRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/e5cd5c9910.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  </head>

  <body>

    <%= yield %>

  </body>
</html>